version: "3.9"
   
services:
  db:
    image: postgres
    ports:
      - "5432:5432"    
    environment:
      - POSTGRES_DB=beqoracle
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  server:
    build: ../server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=beqoracle
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres